### ISSUE TITLE
form parameter, raw body の対応

### ISSUE THREAD

**Issue by sachaos** [aktsk/atgen#15]
JSON ではなく form や raw body をテストのリクエストとして送りたい場合もあるので、
これを記述する際の YAML の形式を考えてみる。

```yaml
# 参考例: 現状の JSON の送信方法
- name: TestPost
  routerFunc: github.com/aktsk/atgen/example.getRouter
  apiVersions:
    - v1
  tests:
    - path: /{apiVersion}/people/3
      method: post
      req:
        params:
          firstname: Jane
          lastname: Doe
      res:
        status: 200
# 提案1: YAML に type を指定する
- name: TestPost
  routerFunc: github.com/aktsk/atgen/example.getRouter
  apiVersions:
    - v1
  tests:
    - path: /{apiVersion}/people/3
      method: post
      req:
        type: form # raw body だったら raw, json だったら json
        params:
          firstname: Jane
          lastname: Doe
      res:
        status: 200
# 提案2: 現状の params フィールドの名前で指定できるようにする
- name: TestPost
  routerFunc: github.com/aktsk/atgen/example.getRouter
  apiVersions:
    - v1
  tests:
    - path: /{apiVersion}/people/3
      method: post
      req:
        form: # raw body だったら raw, json or params だったら json, raw だったら raw で文字列をいれる
          firstname: Jane
          lastname: Doe
      res:
        status: 200
# 提案3: Content Type Header で指定できるようにする
- name: TestPost
  routerFunc: github.com/aktsk/atgen/example.getRouter
  apiVersions:
    - v1
  tests:
    - path: /{apiVersion}/people/3
      method: post
      req:
        headers:
          Content-Type: application/x-www-form-urlencoded # params の変換形式を Content-Type で決める
        params:
          firstname: Jane
          lastname: Doe
      res:
        status: 200
```
