### ISSUE TITLE
Router ではなく HTTPサーバにテストをできるようにする

### ISSUE THREAD

**Issue by sachaos** [aktsk/atgen#20]

**Comment by p1ass** [comment]
##  Routerの使用状況

`net/http/httptest`パッケージを使ってエンドポイントのテストをしているため、`http.Handler`を満たすRouterをyamlから取得して埋め込んでいる。

それ以外の場所では使われていない。

## Routerをやめることのメリット・デメリット

### メリット

- 任意のサーバに対するE2Eテストをyamlで記述することができる。
    - テストをyamlで記述するというのは、Goを書きたくないというモチベが一部含まれているように感じるので、あえてGoだけを対象にすることはないと思われる。


### デメリット

- 生成したテストを実行する際に、事前に対象のサーバを起動しておく必要がある。
    - 今までは直接Goの関数を呼んでテストを実行していたため、事前にサーバを立ち上げる必要はなかった。


## 方針

APIのbase urlをyamlで指定できるようにする。

```yaml
- name: TestGetPerson
  # routerFunc: github.com/aktsk/atgen/example.getRouter
  baseURL: https://api.example.com
  apiVersions:
    - v1
  ...
```
