### ISSUE TITLE
レスポンスの配列内要素を確認できる機能がほしい

### ISSUE THREAD

**Issue by 398noe** [aktsk/atgen#34]
レスポンスが
```json
{
  "lists": [
    {
      "id": "name",
      "age": 20,
    },
    {
      "id": "name2",
      "age": 21,
    }
  ]
}
```
のように返却される場合、`lists[0].id`や`lists[1].age`などの、配列内の要素に対して確認を行う機能が存在しない。以下のような書き方に対応して、配列内の要素に対して確認を行えるよう機能強化してほしい

```yaml
- path: /people
  method: get
  req:
    type: json
  res:
    status: 200
    params:
      lists[0].id: "name"
      lists[1].age: 21
```
