### ISSUE TITLE
register variables

### ISSUE THREAD

**Issue by sachaos** [aktsk/atgen#7]
前のレスポンスの結果を使用して、後続処理を進めるというのは頻出するパターンなので generator で解決できると嬉しそうだなぁと思っています。
イメージとしては Ansible の Register Variables のようなイメージです。
https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html#register-variables

YAML は Ansible の Register Variables を参考にすると以下のようなものを想定しています。

```yaml
- name: TestPostAndCreatePost
  routerFunc: github.com/aktsk/atgen/example.getRouter
  apiVersions:
    - v1
  tests:
    - path: /{apiVersion}/people/3
      method: post
      req:
        params:
          firstname: Jane
          lastname: Doe
      res:
        status: 200
      register: jane # jane に response のオブジェクトを格納する
    - path: /{apiVersion}/people/3/posts
      method: post
      headers:
         authorization: {jane.params.apiKey} # jane にマッピングされている response の値を使用する
      params:
         title: "foo"
         body: "bar"
      res:
        status: 200
```
